steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['install', '.']
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['test', '.']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcbapp-example', '.']
images: ['gcr.io/$PROJECT_ID/gcbapp-example']